### ISSUE TITLE
Vias der AKL Buchsen zu klein

### ISSUE THREAD

**Issue by JanR2311** [IUNO-TDM/MotorShield#1]
Die Breite der Pins der AKL-Buchsen sind Reckteckig und haben die Maße 0,8x0,8 mm.
Vias sind kreisförmig und haben einen Durchmesser von 0,9mm.

--> Größe der Vias müssen auf einen Mindestdurchmesser von 1,6mm vergrößert werden.

**Comment by bockha** [comment]
Die Durchmesser der Pads sind nun zu groß. Passend ist ein Durchmesse von 1,2mm. (0,8 + sqrt(2))
